title: Evelyn
author: evelyn
email: tbd@tbd.com
description: >-
  Short description 
keywords: wip
deploy:
  source: git@github.com:rb-evelyn/evelyn.github.io.git
  branch: production
  dir: _production

baseurl: /
url: https://rb-evelyn.github.io/evelyn.github.io

plugins:
  - jekyll-menus

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - _deploy
  - vendor
